# Generated by Django 3.1.7 on 2021-07-09 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Field', models.CharField(max_length=200, null=True)),
                ('Image', models.FileField(blank=True, upload_to='Icons/')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSlotCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=50, null=True)),
                ('Heading', models.CharField(max_length=33)),
                ('Training_period', models.CharField(blank=True, max_length=30)),
                ('Rate', models.IntegerField(default=1)),
                ('Image', models.FileField(blank=True, upload_to='Cards/')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Trainee_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UploadClassVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trainer', models.CharField(max_length=100)),
                ('Trainer_play', models.CharField(max_length=100)),
                ('f_name', models.CharField(blank=True, default='NULL', max_length=255)),
                ('myfiles', models.FileField(upload_to='ClassVideos')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Name', models.CharField(max_length=33)),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Image', models.FileField(blank=True, default='Icons/dp.jfif', upload_to='UserProfileImage/')),
                ('about', models.CharField(blank=True, max_length=800)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UsersPaymentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Name', models.CharField(max_length=33)),
                ('imageURL', models.CharField(default='null', max_length=3300)),
                ('active', models.BooleanField(default=False)),
                ('expire_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Buying_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('CardId', models.CharField(default='null', max_length=33)),
                ('Trainer_Name', models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Trainer_play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitnessClub_App.trainingslotcard')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingCardDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trainer_Name', models.CharField(default='null', max_length=33)),
                ('Video', models.FileField(blank=True, upload_to='Videos/')),
                ('Seven_Day_Rate', models.IntegerField(default=0)),
                ('One_Month_Rate', models.IntegerField(default=0)),
                ('Three_Months_Rate', models.IntegerField(default=0)),
                ('One_year_Rate', models.IntegerField(default=0)),
                ('Two_year_Rate', models.IntegerField(default=0)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Trainer_play', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='FitnessClub_App.trainingslotcard')),
            ],
        ),
    ]
