# Generated by Django 3.1.7 on 2021-07-09 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessClub_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingslotcard',
            name='Rate',
        ),
    ]
