# Generated by Django 3.1.7 on 2021-07-12 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FitnessClub_App', '0002_remove_trainingslotcard_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userspaymenthistory',
            name='Trainer_Name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
