# Generated by Django 3.1.7 on 2021-07-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessClub_App', '0007_auto_20210712_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userspaymenthistory',
            name='expire_date',
            field=models.CharField(max_length=330),
        ),
    ]
